version: '3'
services:
    mysqld:
        image: oshp/database:develop
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: headers
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
    oshp:
        image: oshp/secureheaders:latest
        depends_on:
          - mysqld
        labels:
          - traefik.enable=true
          - traefik.backend=oshp
          - traefik.port=5000
          - traefik.backend.loadbalancer.method=drr
          - traefik.frontend.rule=PathPrefix:/
    traefik:
        image: traefik:1.3-alpine
        command: --docker --docker.watch --docker.exposedbydefault=false --docker.domain=localhost --web --web.statistics --web.metrics
        ports:
          - 80:80
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    redis:
        image: redis:alpine
