version: '3'
services:
  mysql:
    image: oshp/database:develop
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: headers
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  oshp:
    build:
      context: .
      dockerfile: docker/secureheaders/Dockerfile
    container_name: oshp
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    labels:
      - traefik.enable=true
      - traefik.backend=oshp
      - traefik.port=5000
      - traefik.backend.loadbalancer.method=drr
      - traefik.frontend.rule=PathPrefix:/
    ports:
      - 5000:5000
  proxy:
    image: traefik:maroilles-alpine
    container_name: proxy
    command:
      - --accesslog
      - --api
      - --api.dashboard
      - --api.statistics
      - --api.statistics.recenterrors=10
      - --docker
      - --docker.domain=localhost
      - --docker.watch=true
      - --docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
